spring:
  ## LOCAL DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: TESTUSER
    url: jdbc:mysql://localhost:3306/LIONTEST?characterEncoding=UTF-8&serverTimezone=UTC
    password: '123456'

    ## RDS DB
#  datasource:
#    username: admin
#    url: jdbc:mysql://likelion-backend-study-db.cteiconaamwx.ap-northeast-2.rds.amazonaws.com:3306/LIONTEST
#    password: '12345678'
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 121187965555-elivl2h0srrsa0tdg9430rm9qpml2rnd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
jwt:
  secret: LmFwaS1leGFtcGxlX0RBTi1MSUtFTElPTi0xMVRILVNFSk9ORy11bml2ZXJzaXR5LWJhY2tFbmQtU2V2ZXItRGV2ZWxvcE1lbnQu